// Compile-time check that the hand-written Valibot schemas in schemas/models.ts
// stay in sync with the Go models (types/generated.ts, regenerated by `make generate`).
// `bun run typecheck`, part of `make test`, fails when they drift apart.
//
// For each object model the field names must match exactly, and for every model
// the schema must accept what the Go server sends (the generated type is
// assignable to the schema input).
// Value types may still differ where a schema is deliberately more tolerant,
// e.g. a defaulted or nullish field.
import type * as v from 'valibot'
import type * as s from '../schemas/models'
import type * as gen from './generated'

type Equal<A, B> =
	(<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
		? true
		: false
type Assert<T extends true> = T

type InSync<Schema extends v.GenericSchema, Go> = [
	[Go] extends [object] ? Equal<keyof v.InferInput<Schema>, keyof Go> : true,
	[Go] extends [v.InferInput<Schema>] ? true : false,
] extends [true, true]
	? true
	: false

export type DriftChecks = [
	Assert<InSync<typeof s.PrioritySchema, gen.Priority>>,
	Assert<InSync<typeof s.MilestoneStatusSchema, gen.MilestoneStatus>>,
	Assert<InSync<typeof s.TierSchema, gen.Tier>>,
	Assert<InSync<typeof s.ColumnSchema, gen.Column>>,
	Assert<InSync<typeof s.TaskSchema, gen.Task>>,
	Assert<InSync<typeof s.MilestoneSchema, gen.Milestone>>,
	Assert<InSync<typeof s.StrategySchema, gen.Strategy>>,
	Assert<InSync<typeof s.GlossaryTermSchema, gen.GlossaryTerm>>,
	Assert<InSync<typeof s.ProjectConfigSchema, gen.ProjectConfig>>,
	Assert<InSync<typeof s.BoardConfigSchema, gen.BoardConfig>>,
	Assert<InSync<typeof s.TagsConfigSchema, gen.TagsConfig>>,
	Assert<InSync<typeof s.BuildConfigSchema, gen.BuildConfig>>,
	Assert<InSync<typeof s.PriorityConfigSchema, gen.PriorityConfig>>,
	Assert<InSync<typeof s.TierConfigSchema, gen.TierConfig>>,
	Assert<InSync<typeof s.MCPConfigSchema, gen.MCPConfig>>,
	Assert<InSync<typeof s.SnapshotConfigSchema, gen.SnapshotConfig>>,
	Assert<InSync<typeof s.SnapshotSchema, gen.Snapshot>>,
	Assert<InSync<typeof s.ColumnStateSchema, gen.ColumnState>>,
	Assert<InSync<typeof s.BoardStateSchema, gen.BoardState>>,
]
