// Code generated by cmd/gentypes from internal/model. DO NOT EDIT.
// Run 'make generate' to regenerate.

export type Priority = string;

export type MilestoneStatus = "open" | "closed";

export type Tier = 1 | 2 | 3;

export interface BoardConfig {
  columns: Column[];
  editable_states?: string[];
  creatable_states?: string[];
  default_create_state?: string;
}

export interface BoardState {
  project_name: string;
  columns: ColumnState[];
  editable_states?: string[];
  creatable_states?: string[];
  default_create_state?: string;
  mcp_instructions?: string;
}

export interface BuildConfig {
  time?: string;
  branch?: string;
  commit?: string;
  version?: string;
}

export interface Column {
  id: string;
  name: string;
  color: string;
  handled_by?: string;
  instructions?: string;
  sort_by?: string;
  sort_direction?: string;
}

export interface ColumnState {
  id: string;
  name: string;
  color: string;
  handled_by?: string;
  instructions?: string;
  sort_by?: string;
  sort_direction?: string;
  tasks: Task[];
  count: number;
}

export interface FilterCriteria {
  status?: string;
  milestone?: string;
  tag?: string;
  priority?: Priority;
  search_query?: string;
}

export interface GlossaryFrontmatter {
  title: string;
  tags: string[];
  summary: string;
}

export interface GlossaryTerm {
  id: string;
  title: string;
  tags: string[];
  summary: string;
  body?: string;
  body_html?: string;
  file_path?: string;
  mod_time?: string;
}

export interface MCPConfig {
  instructions?: string;
}

export interface Milestone {
  id: string;
  title: string;
  status: MilestoneStatus;
  is_archived: boolean;
  target_date?: string;
  target_start_at?: string;
  target_end_at?: string;
  target_timeframe?: string;
  tags: string[];
  summary: string;
  body?: string;
  body_html?: string;
  total_tasks: number;
  completed_tasks: number;
  progress_percentage: number;
  file_path?: string;
  mod_time?: string;
}

export interface MilestoneFrontmatter {
  title: string;
  status: MilestoneStatus;
  target_date?: string;
  tags: string[];
  summary: string;
}

export interface PriorityConfig {
  id: string;
  name: string;
  color?: string;
}

export interface ProjectConfig {
  name: string;
  description?: string;
}

export interface SearchResult {
  id: string;
  type?: string;
  title: string;
  tags: string[];
  snippet: string;
  score: number;
  status?: string;
  priority?: Priority;
  target_date?: string;
  tier?: Tier;
}

export interface Snapshot {
  config: SnapshotConfig;
  tasks: Task[];
  milestones: Milestone[];
  strategies: Strategy[];
  glossary: GlossaryTerm[];
}

export interface SnapshotConfig {
  project: ProjectConfig;
  board: BoardConfig;
  priorities?: PriorityConfig[];
  tiers?: TierConfig[];
  tags?: TagsConfig;
  build?: BuildConfig;
  translations?: TranslationsConfig;
  mcp?: MCPConfig;
}

export interface Strategy {
  id: string;
  title: string;
  tier: Tier;
  tags: string[];
  summary: string;
  body?: string;
  body_html?: string;
  file_path?: string;
  mod_time?: string;
}

export interface StrategyFrontmatter {
  title: string;
  tier: Tier;
  tags: string[];
  summary: string;
}

export interface TagCount {
  tag: string;
  task_count: number;
  milestone_count: number;
  strategy_count: number;
}

export interface TagList {
  enforced: boolean;
  tags: TagCount[];
}

export interface TagsConfig {
  allowed?: string[];
  enforce_allowed: boolean;
}

export interface Task {
  id: string;
  title: string;
  status: string;
  priority: Priority;
  milestone?: string;
  tags: string[];
  summary: string;
  dependencies: string[];
  body?: string;
  body_html?: string;
  total_criteria?: number;
  completed_criteria?: number;
  file_path?: string;
  mod_time?: string;
  created_at?: string;
  changed_at?: string;
  target_at?: string;
}

export interface TaskFrontmatter {
  title: string;
  status: string;
  priority?: Priority;
  milestone?: string;
  tags: string[];
  summary: string;
  dependencies?: string[];
  created_at?: string;
  changed_at?: string;
  target_at?: string;
}

export interface TierConfig {
  id: string;
  name: string;
  title: string;
  summary: string;
  color?: string;
}

export interface TranslationsConfig {
  board?: string;
  strategies?: string;
  glossary?: string;
  milestones?: string;
  search?: string;
  tasks?: string;
  architectural_strategies?: string;
  strategies_subtitle?: string;
  tiers?: string;
  all_tiers?: string;
  project_glossary?: string;
  glossary_subtitle?: string;
  footer_text?: string;
  reset?: string;
  no_tasks?: string;
  no_matching_results?: string;
  no_matches_current_page?: string;
  no_matches_other_pages?: string;
  show_completed?: string;
  hide_completed?: string;
  show_archived?: string;
  sort_by?: string;
  sort_default?: string;
  sort_priority?: string;
  sort_target_at?: string;
  sort_changed_at?: string;
  sort_created_at?: string;
  sort_title?: string;
  arial_main_nav?: string;
  arial_mobile_nav?: string;
  arial_mobile_menu?: string;
  arial_open_menu?: string;
  arial_close_menu?: string;
  arial_search?: string;
  arial_search_input?: string;
  arial_search_results?: string;
  arial_theme_toggle?: string;
  arial_theme_dark?: string;
  arial_theme_light_label?: string;
  arial_theme_dark_label?: string;
  arial_filter_tasks?: string;
  arial_filter_by_priority?: string;
  arial_filter_by_tags?: string;
  arial_reset_all_filters?: string;
  arial_sort_tasks?: string;
  arial_sort_options?: string;
  arial_column_quick_nav?: string;
  arial_kanban_columns?: string;
  arial_milestones_roadmap?: string;
  arial_footer?: string;
  arial_github_repo?: string;
}

export type SSEEventType =
  | "task.created"
  | "task.updated"
  | "task.deleted"
  | "milestone.created"
  | "milestone.updated"
  | "milestone.deleted"
  | "board.refreshed"
  | "ping";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  payload?: T;
}
