// Code generated by cmd/gentypes from internal/model. DO NOT EDIT.
// Run 'make generate' to regenerate.

export type Priority = "low" | "medium" | "high" | "critical";

export type MilestoneStatus = "open" | "closed";

export type Tier = 1 | 2 | 3;

export interface BoardConfig {
  columns: Column[];
}

export interface BoardState {
  project_name: string;
  columns: ColumnState[];
}

export interface BuildConfig {
  time?: string;
  branch?: string;
  commit?: string;
}

export interface Column {
  id: string;
  name: string;
  color: string;
}

export interface ColumnState {
  id: string;
  name: string;
  color: string;
  tasks: Task[];
  count: number;
}

export interface FilterCriteria {
  status?: string;
  milestone?: string;
  tag?: string;
  priority?: Priority;
  search_query?: string;
}

export interface GlossaryFrontmatter {
  title: string;
  tags: string[];
  summary: string;
}

export interface GlossaryTerm {
  id: string;
  title: string;
  tags: string[];
  summary: string;
  body?: string;
  file_path?: string;
  mod_time?: string;
}

export interface Milestone {
  id: string;
  title: string;
  status: MilestoneStatus;
  is_archived: boolean;
  target_date?: string;
  tags: string[];
  summary: string;
  body?: string;
  total_tasks: number;
  completed_tasks: number;
  progress_percentage: number;
  file_path?: string;
  mod_time?: string;
}

export interface MilestoneFrontmatter {
  title: string;
  status: MilestoneStatus;
  target_date?: string;
  tags: string[];
  summary: string;
}

export interface ProjectConfig {
  name: string;
  description?: string;
}

export interface SearchResult {
  id: string;
  type?: string;
  title: string;
  tags: string[];
  snippet: string;
  score: number;
  status?: string;
  priority?: Priority;
  target_date?: string;
  tier?: Tier;
}

export interface Snapshot {
  config: SnapshotConfig;
  tasks: Task[];
  milestones: Milestone[];
  strategies: Strategy[];
  glossary: GlossaryTerm[];
}

export interface SnapshotConfig {
  project: ProjectConfig;
  board: BoardConfig;
  tags?: TagsConfig;
  build?: BuildConfig;
}

export interface Strategy {
  id: string;
  title: string;
  tier: Tier;
  tags: string[];
  summary: string;
  body?: string;
  file_path?: string;
  mod_time?: string;
}

export interface StrategyFrontmatter {
  title: string;
  tier: Tier;
  tags: string[];
  summary: string;
}

export interface TagCount {
  tag: string;
  task_count: number;
  milestone_count: number;
  strategy_count: number;
}

export interface TagList {
  enforced: boolean;
  tags: TagCount[];
}

export interface TagsConfig {
  allowed?: string[];
  enforce_allowed: boolean;
}

export interface Task {
  id: string;
  title: string;
  status: string;
  priority: Priority;
  milestone?: string;
  tags: string[];
  summary: string;
  dependencies: string[];
  body?: string;
  total_criteria?: number;
  completed_criteria?: number;
  file_path?: string;
  mod_time?: string;
}

export interface TaskFrontmatter {
  title: string;
  status: string;
  priority?: Priority;
  milestone?: string;
  tags: string[];
  summary: string;
  dependencies?: string[];
}

export type SSEEventType =
  | "task.created"
  | "task.updated"
  | "task.deleted"
  | "milestone.created"
  | "milestone.updated"
  | "milestone.deleted"
  | "board.refreshed"
  | "ping";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  payload?: T;
}
