// Package main provides a lightweight pure Go AST parser that reads domain models
// from internal/model and emits type-safe TypeScript interfaces to web/src/types/generated.ts.
//
// The generated interfaces mirror what encoding/json produces for each struct:
//
//   - Field names come from the json tag, or the Go field name verbatim when the tag
//     has no name. Unexported fields and fields tagged `json:"-"` are skipped.
//   - omitempty / omitzero mark a field optional (`name?: T`).
//   - A pointer `*T` is nullable: without omitempty/omitzero a nil pointer encodes as
//     null (`name: T | null`); with them it is omitted (`name?: T`). Pointers inside
//     slices and maps keep the null (`(T | null)[]`, `Record<string, T | null>`).
//     `*time.Time` follows the same rule with `string` as the element type.
//   - Untagged embedded structs from the model package (including unexported and
//     pointer embeds) are flattened into the parent, following the encoding/json
//     promotion and dominance rules. Fields promoted through an embedded pointer are
//     optional, because a nil pointer omits them. Tagged embedded fields and embedded
//     non-struct types are regular named fields.
//   - Types the generator cannot express (types from other packages except
//     time.Time, generics, funcs, chans) are written as `unknown` or skipped, and a
//     warning is printed on stderr.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
)

func main() {
	modelDir := flag.String("models", "internal/model", "Directory containing Go model source files")
	outFile := flag.String("out", "web/src/types/generated.ts", "Output TypeScript file path")
	flag.Parse()

	out, err := generate(*modelDir, os.Stderr)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(*outFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create directory for %q: %v\n", *outFile, err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outFile, out, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write output file %q: %v\n", *outFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated TypeScript models in %s\n", *outFile)
}

// generate parses package model in modelDir and returns the TypeScript source.
// Warnings about unsupported constructs are written to warn.
func generate(modelDir string, warn io.Writer) ([]byte, error) {
	fset := token.NewFileSet()
	notTest := func(fi fs.FileInfo) bool { return !strings.HasSuffix(fi.Name(), "_test.go") }
	pkgs, err := parser.ParseDir(fset, modelDir, notTest, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("failed to parse models directory %q: %v", modelDir, err)
	}

	pkg, ok := pkgs["model"]
	if !ok {
		return nil, fmt.Errorf("package 'model' not found in %q", modelDir)
	}

	g := &generator{structs: make(map[string]*ast.StructType), warn: warn}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gentypes from internal/model. DO NOT EDIT.\n")
	buf.WriteString("// Run 'make generate' to regenerate.\n\n")

	// 1. Static enums / union types
	buf.WriteString("export type Priority = string;\n\n")
	buf.WriteString("export type MilestoneStatus = \"open\" | \"closed\";\n\n")
	buf.WriteString("export type Tier = 1 | 2 | 3;\n\n")

	// 2. Discover all struct types. Unexported structs are kept for embedding lookups
	// but only exported ones are emitted, in alphabetical order.
	var structNames []string
	for _, fileName := range slices.Sorted(maps.Keys(pkg.Files)) {
		for _, decl := range pkg.Files[fileName].Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				name := typeSpec.Name.Name
				if typeSpec.TypeParams != nil {
					g.warnf("%s: generic struct types are not supported; skipped", name)
					continue
				}
				g.structs[name] = structType
				if ast.IsExported(name) {
					structNames = append(structNames, name)
				}
			}
		}
	}

	slices.Sort(structNames)

	for _, name := range structNames {
		fmt.Fprintf(&buf, "export interface %s {\n", name)
		for _, f := range g.resolveFields(name) {
			optSuffix := ""
			if f.optional {
				optSuffix = "?"
			}
			fmt.Fprintf(&buf, "  %s%s: %s;\n", f.name, optSuffix, f.tsType)
		}
		buf.WriteString("}\n\n")
	}

	// 3. SSE event types
	buf.WriteString(`export type SSEEventType =
  | "task.created"
  | "task.updated"
  | "task.deleted"
  | "milestone.created"
  | "milestone.updated"
  | "milestone.deleted"
  | "strategy.created"
  | "strategy.updated"
  | "strategy.deleted"
  | "glossary.created"
  | "glossary.updated"
  | "glossary.deleted"
  | "ping";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  payload?: T;
}
`)

	return buf.Bytes(), nil
}

// generator holds the struct declarations of the model package and the warning sink.
type generator struct {
	structs map[string]*ast.StructType
	warn    io.Writer
}

func (g *generator) warnf(format string, args ...any) {
	if g.warn != nil {
		fmt.Fprintf(g.warn, "gentypes: warning: "+format+"\n", args...)
	}
}

// tsField is one JSON key of a struct, before dominance resolution.
type tsField struct {
	name     string
	tsType   string
	optional bool
	depth    int  // embedding depth, 0 for the struct's own fields
	tagged   bool // name came from a json tag
}

// resolveFields returns the JSON keys of struct name in encoding/json order,
// applying its rules for fields promoted from embedded structs: the shallowest
// field wins, a tagged field wins over untagged ones at the same depth, and any
// other name collision drops the name entirely.
func (g *generator) resolveFields(name string) []tsField {
	all := g.collectFields(name, g.structs[name], 0, false, map[string]bool{name: true})

	byName := make(map[string][]int)
	for i, f := range all {
		byName[f.name] = append(byName[f.name], i)
	}

	var out []tsField
	for i, f := range all {
		idx := byName[f.name]
		winner, ok := dominantField(all, idx)
		if !ok && idx[0] == i {
			g.warnf("%s.%s: ambiguous field name at the same embedding depth; encoding/json drops it", name, f.name)
		}
		if ok && winner == i {
			out = append(out, f)
		}
	}
	return out
}

// dominantField mirrors encoding/json's dominantField: it returns the index of the
// winning field among candidates, or ok=false when the name is ambiguous.
func dominantField(all []tsField, idx []int) (winner int, ok bool) {
	sorted := slices.Clone(idx)
	slices.SortStableFunc(sorted, func(a, b int) int {
		if all[a].depth != all[b].depth {
			return all[a].depth - all[b].depth
		}
		if all[a].tagged != all[b].tagged {
			if all[a].tagged {
				return -1
			}
			return 1
		}
		return 0
	})
	if len(sorted) > 1 && all[sorted[0]].depth == all[sorted[1]].depth && all[sorted[0]].tagged == all[sorted[1]].tagged {
		return -1, false
	}
	return sorted[0], true
}

// collectFields flattens st into JSON keys in declaration order. viaPtr reports
// whether st was reached through an embedded pointer; visited guards against
// recursive embedding.
func (g *generator) collectFields(owner string, st *ast.StructType, depth int, viaPtr bool, visited map[string]bool) []tsField {
	var out []tsField
	for _, field := range st.Fields.List {
		tagVal := ""
		if field.Tag != nil {
			tagVal = field.Tag.Value
		}
		jsonTag := reflect.StructTag(strings.Trim(tagVal, "`")).Get("json")
		if jsonTag == "-" {
			continue
		}
		tagName, opts, _ := strings.Cut(jsonTag, ",")
		omit := slices.ContainsFunc(strings.Split(opts, ","), func(o string) bool {
			return o == "omitempty" || o == "omitzero"
		})

		if len(field.Names) == 0 {
			out = append(out, g.embeddedField(owner, field.Type, tagName, omit, depth, viaPtr, visited)...)
			continue
		}

		for _, ident := range field.Names {
			if !ident.IsExported() {
				continue
			}
			name := tagName
			if name == "" {
				name = ident.Name
			}
			warn := func(msg string) { g.warnf("%s.%s: %s", owner, ident.Name, msg) }
			out = append(out, newField(name, field.Type, tagName != "", omit, depth, viaPtr, warn))
		}
	}
	return out
}

// embeddedField handles an anonymous struct field with type expr.
func (g *generator) embeddedField(owner string, expr ast.Expr, tagName string, omit bool, depth int, viaPtr bool, visited map[string]bool) []tsField {
	base, isPtr := expr, false
	if star, ok := expr.(*ast.StarExpr); ok {
		base, isPtr = star.X, true
	}
	typeName := embeddedTypeName(base)
	warn := func(msg string) { g.warnf("%s.%s: %s", owner, typeName, msg) }

	switch b := base.(type) {
	case *ast.Ident:
		st, isStruct := g.structs[b.Name]
		switch {
		case tagName != "":
			return []tsField{newField(tagName, expr, true, omit, depth, viaPtr, warn)}
		case isStruct:
			if visited[b.Name] {
				return nil
			}
			visited[b.Name] = true
			defer delete(visited, b.Name)
			return g.collectFields(owner, st, depth+1, viaPtr || isPtr, visited)
		case b.IsExported():
			// An embedded non-struct type is a field named after the type.
			return []tsField{newField(b.Name, expr, false, omit, depth, viaPtr, warn)}
		default:
			return nil
		}
	case *ast.SelectorExpr:
		if tagName != "" {
			return []tsField{newField(tagName, expr, true, omit, depth, viaPtr, warn)}
		}
		warn("embedded type from another package is not supported; its fields are skipped")
	case *ast.IndexExpr, *ast.IndexListExpr:
		warn("embedded generic type is not supported; its fields are skipped")
	default:
		warn("unsupported embedded type; skipped")
	}
	return nil
}

// embeddedTypeName returns a readable name for an embedded type expression.
func embeddedTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return embeddedTypeName(t.X) + "." + t.Sel.Name
	case *ast.IndexExpr:
		return embeddedTypeName(t.X)
	case *ast.IndexListExpr:
		return embeddedTypeName(t.X)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// newField builds a tsField. A top-level pointer becomes optional with its element
// type when omitempty/omitzero is set, and `T | null` otherwise.
func newField(name string, expr ast.Expr, tagged, omit bool, depth int, viaPtr bool, warn func(string)) tsField {
	if star, ok := expr.(*ast.StarExpr); ok && omit {
		expr = star.X
	}
	return tsField{
		name:     name,
		tsType:   goTypeToTS(expr, warn),
		optional: omit || viaPtr,
		depth:    depth,
		tagged:   tagged,
	}
}

// goTypeToTS maps a Go type expression to TypeScript. Unsupported types map to
// "unknown" and are reported through warn, which may be nil.
func goTypeToTS(expr ast.Expr, warn func(string)) string {
	unsupported := func(what string) string {
		if warn != nil {
			warn(what + " is not supported; written as unknown")
		}
		return "unknown"
	}
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return "number"
		case "bool":
			return "boolean"
		default:
			return t.Name
		}
	case *ast.StarExpr:
		elem := goTypeToTS(t.X, warn)
		if strings.HasSuffix(elem, " | null") {
			return elem
		}
		return elem + " | null"
	case *ast.ArrayType:
		if ident, ok := t.Elt.(*ast.Ident); ok && t.Len == nil && (ident.Name == "byte" || ident.Name == "uint8") {
			return "string" // []byte is base64-encoded
		}
		elem := goTypeToTS(t.Elt, warn)
		if strings.Contains(elem, " | ") {
			elem = "(" + elem + ")"
		}
		return elem + "[]"
	case *ast.MapType:
		val := goTypeToTS(t.Value, warn)
		return fmt.Sprintf("Record<string, %s>", val)
	case *ast.SelectorExpr:
		if ident, ok := t.X.(*ast.Ident); ok && ident.Name == "time" && t.Sel.Name == "Time" {
			return "string" // ISO-8601 string in JSON
		}
		return unsupported("type " + embeddedTypeName(t) + " from another package")
	case *ast.InterfaceType:
		return "unknown"
	case *ast.IndexExpr, *ast.IndexListExpr:
		return unsupported("generic type " + embeddedTypeName(t))
	case *ast.FuncType:
		return unsupported("func type")
	case *ast.ChanType:
		return unsupported("chan type")
	default:
		return unsupported(fmt.Sprintf("type %T", expr))
	}
}
