// Package main provides a lightweight pure Go AST parser that reads domain models
// from internal/model and emits type-safe TypeScript interfaces to web/src/types/generated.ts.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
)

func main() {
	modelDir := flag.String("models", "internal/model", "Directory containing Go model source files")
	outFile := flag.String("out", "web/src/types/generated.ts", "Output TypeScript file path")
	flag.Parse()

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, *modelDir, nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse models directory %q: %v\n", *modelDir, err)
		os.Exit(1)
	}

	pkg, ok := pkgs["model"]
	if !ok {
		fmt.Fprintf(os.Stderr, "package 'model' not found in %q\n", *modelDir)
		os.Exit(1)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gentypes from internal/model. DO NOT EDIT.\n")
	buf.WriteString("// Run 'make generate' to regenerate.\n\n")

	// 1. Static enums / union types
	buf.WriteString("export type Priority = \"low\" | \"medium\" | \"high\" | \"critical\";\n\n")
	buf.WriteString("export type MilestoneStatus = \"open\" | \"closed\";\n\n")
	buf.WriteString("export type Tier = 1 | 2 | 3;\n\n")

	// 2. Discover all struct types in alphabetical order
	structNames := make([]string, 0)
	structDecls := make(map[string]*ast.StructType)

	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				name := typeSpec.Name.Name
				// Skip non-exported or specific private structs if any
				if !ast.IsExported(name) {
					continue
				}
				structNames = append(structNames, name)
				structDecls[name] = structType
			}
		}
	}

	slices.Sort(structNames)

	for _, name := range structNames {
		st := structDecls[name]
		fmt.Fprintf(&buf, "export interface %s {\n", name)

		for _, field := range st.Fields.List {
			tagVal := ""
			if field.Tag != nil {
				tagVal = field.Tag.Value
			}

			jsonTag := reflect.StructTag(strings.Trim(tagVal, "`")).Get("json")
			if jsonTag == "-" {
				continue
			}

			fieldName := ""
			optional := false

			if jsonTag != "" {
				parts := strings.Split(jsonTag, ",")
				fieldName = parts[0]
				if slices.Contains(parts[1:], "omitempty") || slices.Contains(parts[1:], "omitzero") {
					optional = true
				}
			}

			if fieldName == "" && len(field.Names) > 0 {
				fieldName = lowerFirst(field.Names[0].Name)
			}

			if fieldName == "" {
				continue
			}

			tsType := goTypeToTS(field.Type)
			optSuffix := ""
			if optional {
				optSuffix = "?"
			}

			fmt.Fprintf(&buf, "  %s%s: %s;\n", fieldName, optSuffix, tsType)
		}

		buf.WriteString("}\n\n")
	}

	// 3. SSE event types
	buf.WriteString(`export type SSEEventType =
  | "task.created"
  | "task.updated"
  | "task.deleted"
  | "milestone.created"
  | "milestone.updated"
  | "milestone.deleted"
  | "board.refreshed"
  | "ping";

export interface SSEEvent<T = unknown> {
  type: SSEEventType;
  payload?: T;
}
`)

	if err := os.MkdirAll(filepath.Dir(*outFile), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create directory for %q: %v\n", *outFile, err)
		os.Exit(1)
	}

	if err := os.WriteFile(*outFile, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write output file %q: %v\n", *outFile, err)
		os.Exit(1)
	}

	fmt.Printf("Generated TypeScript models in %s\n", *outFile)
}

func lowerFirst(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func goTypeToTS(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string"
		case "int", "int64", "int32", "uint", "uint64", "uint32", "float64", "float32":
			return "number"
		case "bool":
			return "boolean"
		case "Priority":
			return "Priority"
		case "MilestoneStatus":
			return "MilestoneStatus"
		case "Tier":
			return "Tier"
		default:
			return t.Name
		}
	case *ast.ArrayType:
		elem := goTypeToTS(t.Elt)
		return fmt.Sprintf("%s[]", elem)
	case *ast.MapType:
		val := goTypeToTS(t.Value)
		return fmt.Sprintf("Record<string, %s>", val)
	case *ast.SelectorExpr:
		if ident, ok := t.X.(*ast.Ident); ok && ident.Name == "time" && t.Sel.Name == "Time" {
			return "string" // ISO-8601 string in JSON
		}
		return "unknown"
	case *ast.InterfaceType:
		return "unknown"
	default:
		return "unknown"
	}
}
