// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type EntityTag struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Tag        string `json:"tag"`
}

type FtsEntity struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Title      string `json:"title"`
	Summary    string `json:"summary"`
	Body       string `json:"body"`
}

type Glossary struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Summary  string `json:"summary"`
	Body     string `json:"body"`
	Filepath string `json:"filepath"`
	Mtime    int64  `json:"mtime"`
}

type Milestone struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Status     string `json:"status"`
	TargetDate string `json:"target_date"`
	Summary    string `json:"summary"`
	Body       string `json:"body"`
	Filepath   string `json:"filepath"`
	Mtime      int64  `json:"mtime"`
}

type Strategy struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Tier     int64  `json:"tier"`
	Summary  string `json:"summary"`
	Body     string `json:"body"`
	Filepath string `json:"filepath"`
	Mtime    int64  `json:"mtime"`
}

type Task struct {
	ID                string `json:"id"`
	Title             string `json:"title"`
	Status            string `json:"status"`
	Priority          string `json:"priority"`
	MilestoneID       string `json:"milestone_id"`
	Summary           string `json:"summary"`
	Body              string `json:"body"`
	TotalCriteria     int64  `json:"total_criteria"`
	CompletedCriteria int64  `json:"completed_criteria"`
	Filepath          string `json:"filepath"`
	Mtime             int64  `json:"mtime"`
}

type TaskDependency struct {
	TaskID          string `json:"task_id"`
	DependsOnTaskID string `json:"depends_on_task_id"`
}
