// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AddEntityTag(ctx context.Context, arg AddEntityTagParams) error
	AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error
	// Tags
	ClearEntityTags(ctx context.Context, arg ClearEntityTagsParams) error
	// Dependencies
	ClearTaskDependencies(ctx context.Context, taskID string) error
	CountUnfinishedDependencies(ctx context.Context, taskID string) (int64, error)
	DeleteFTSEntity(ctx context.Context, arg DeleteFTSEntityParams) error
	DeleteGlossaryTerm(ctx context.Context, id string) error
	DeleteMilestone(ctx context.Context, id string) error
	DeleteStrategy(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id string) error
	GetDownstreamTasks(ctx context.Context, dependsOnTaskID string) ([]GetDownstreamTasksRow, error)
	GetEntityTags(ctx context.Context, arg GetEntityTagsParams) ([]string, error)
	GetGlossaryTerm(ctx context.Context, id string) (Glossary, error)
	GetMilestone(ctx context.Context, id string) (Milestone, error)
	GetMilestoneTaskMetrics(ctx context.Context, milestoneID string) (GetMilestoneTaskMetricsRow, error)
	GetStrategy(ctx context.Context, id string) (Strategy, error)
	GetTagCounts(ctx context.Context) ([]GetTagCountsRow, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetTaskDependencies(ctx context.Context, taskID string) ([]string, error)
	// Full-Text Search (FTS5)
	InsertFTSEntity(ctx context.Context, arg InsertFTSEntityParams) error
	ListGlossaryTerms(ctx context.Context) ([]Glossary, error)
	ListMilestones(ctx context.Context) ([]Milestone, error)
	ListStrategies(ctx context.Context) ([]Strategy, error)
	ListStrategiesByTier(ctx context.Context, tier int64) ([]Strategy, error)
	ListTasks(ctx context.Context) ([]Task, error)
	UpdateTaskCriteria(ctx context.Context, arg UpdateTaskCriteriaParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	// Glossary
	UpsertGlossaryTerm(ctx context.Context, arg UpsertGlossaryTermParams) error
	// Milestones
	UpsertMilestone(ctx context.Context, arg UpsertMilestoneParams) error
	// Strategies
	UpsertStrategy(ctx context.Context, arg UpsertStrategyParams) error
	// Tasks
	UpsertTask(ctx context.Context, arg UpsertTaskParams) error
}

var _ Querier = (*Queries)(nil)
