// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const addEntityTag = `-- name: AddEntityTag :exec
INSERT OR IGNORE INTO entity_tags (entity_type, entity_id, tag)
VALUES (?, ?, ?)
`

type AddEntityTagParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Tag        string `json:"tag"`
}

func (q *Queries) AddEntityTag(ctx context.Context, arg AddEntityTagParams) error {
	_, err := q.db.ExecContext(ctx, addEntityTag, arg.EntityType, arg.EntityID, arg.Tag)
	return err
}

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT OR IGNORE INTO task_dependencies (task_id, depends_on_task_id)
VALUES (?, ?)
`

type AddTaskDependencyParams struct {
	TaskID          string `json:"task_id"`
	DependsOnTaskID string `json:"depends_on_task_id"`
}

func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, addTaskDependency, arg.TaskID, arg.DependsOnTaskID)
	return err
}

const clearEntityTags = `-- name: ClearEntityTags :exec
DELETE FROM entity_tags WHERE entity_type = ? AND entity_id = ?
`

type ClearEntityTagsParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

// Tags
func (q *Queries) ClearEntityTags(ctx context.Context, arg ClearEntityTagsParams) error {
	_, err := q.db.ExecContext(ctx, clearEntityTags, arg.EntityType, arg.EntityID)
	return err
}

const clearTaskDependencies = `-- name: ClearTaskDependencies :exec
DELETE FROM task_dependencies WHERE task_id = ?
`

// Dependencies
func (q *Queries) ClearTaskDependencies(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, clearTaskDependencies, taskID)
	return err
}

const countUnfinishedDependencies = `-- name: CountUnfinishedDependencies :one
SELECT COUNT(*)
FROM task_dependencies td
JOIN tasks t ON td.depends_on_task_id = t.id
WHERE td.task_id = ? AND t.status != 'done'
`

func (q *Queries) CountUnfinishedDependencies(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnfinishedDependencies, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFTSEntity = `-- name: DeleteFTSEntity :exec
DELETE FROM fts_entities WHERE entity_type = ? AND entity_id = ?
`

type DeleteFTSEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) DeleteFTSEntity(ctx context.Context, arg DeleteFTSEntityParams) error {
	_, err := q.db.ExecContext(ctx, deleteFTSEntity, arg.EntityType, arg.EntityID)
	return err
}

const deleteGlossaryTerm = `-- name: DeleteGlossaryTerm :exec
DELETE FROM glossary WHERE id = ?
`

func (q *Queries) DeleteGlossaryTerm(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGlossaryTerm, id)
	return err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones WHERE id = ?
`

func (q *Queries) DeleteMilestone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMilestone, id)
	return err
}

const deleteStrategy = `-- name: DeleteStrategy :exec
DELETE FROM strategies WHERE id = ?
`

func (q *Queries) DeleteStrategy(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteStrategy, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getDownstreamTasks = `-- name: GetDownstreamTasks :many
SELECT t.id, t.title, t.status
FROM task_dependencies td
JOIN tasks t ON td.task_id = t.id
WHERE td.depends_on_task_id = ?
`

type GetDownstreamTasksRow struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
}

func (q *Queries) GetDownstreamTasks(ctx context.Context, dependsOnTaskID string) ([]GetDownstreamTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getDownstreamTasks, dependsOnTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDownstreamTasksRow{}
	for rows.Next() {
		var i GetDownstreamTasksRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTags = `-- name: GetEntityTags :many
SELECT tag
FROM entity_tags
WHERE entity_type = ? AND entity_id = ?
ORDER BY tag ASC
`

type GetEntityTagsParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetEntityTags(ctx context.Context, arg GetEntityTagsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEntityTags, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlossaryTerm = `-- name: GetGlossaryTerm :one
SELECT id, title, summary, body, filepath, mtime
FROM glossary
WHERE id = ?
`

func (q *Queries) GetGlossaryTerm(ctx context.Context, id string) (Glossary, error) {
	row := q.db.QueryRowContext(ctx, getGlossaryTerm, id)
	var i Glossary
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Body,
		&i.Filepath,
		&i.Mtime,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, title, status, target_date, summary, body, filepath, mtime
FROM milestones
WHERE id = ?
`

func (q *Queries) GetMilestone(ctx context.Context, id string) (Milestone, error) {
	row := q.db.QueryRowContext(ctx, getMilestone, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.TargetDate,
		&i.Summary,
		&i.Body,
		&i.Filepath,
		&i.Mtime,
	)
	return i, err
}

const getMilestoneTaskMetrics = `-- name: GetMilestoneTaskMetrics :one
SELECT
    COUNT(*) AS total_tasks,
    COUNT(CASE WHEN status = 'done' THEN 1 END) AS completed_tasks
FROM tasks
WHERE milestone_id = ?
`

type GetMilestoneTaskMetricsRow struct {
	TotalTasks     int64 `json:"total_tasks"`
	CompletedTasks int64 `json:"completed_tasks"`
}

func (q *Queries) GetMilestoneTaskMetrics(ctx context.Context, milestoneID string) (GetMilestoneTaskMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getMilestoneTaskMetrics, milestoneID)
	var i GetMilestoneTaskMetricsRow
	err := row.Scan(&i.TotalTasks, &i.CompletedTasks)
	return i, err
}

const getStrategy = `-- name: GetStrategy :one
SELECT id, title, tier, summary, body, filepath, mtime
FROM strategies
WHERE id = ?
`

func (q *Queries) GetStrategy(ctx context.Context, id string) (Strategy, error) {
	row := q.db.QueryRowContext(ctx, getStrategy, id)
	var i Strategy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Tier,
		&i.Summary,
		&i.Body,
		&i.Filepath,
		&i.Mtime,
	)
	return i, err
}

const getTagCounts = `-- name: GetTagCounts :many
SELECT
    tag,
    COUNT(CASE WHEN entity_type = 'task' THEN 1 END) AS task_count,
    COUNT(CASE WHEN entity_type = 'milestone' THEN 1 END) AS milestone_count,
    COUNT(CASE WHEN entity_type = 'strategy' THEN 1 END) AS strategy_count
FROM entity_tags
GROUP BY tag
ORDER BY tag ASC
`

type GetTagCountsRow struct {
	Tag            string `json:"tag"`
	TaskCount      int64  `json:"task_count"`
	MilestoneCount int64  `json:"milestone_count"`
	StrategyCount  int64  `json:"strategy_count"`
}

func (q *Queries) GetTagCounts(ctx context.Context) ([]GetTagCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagCountsRow{}
	for rows.Next() {
		var i GetTagCountsRow
		if err := rows.Scan(
			&i.Tag,
			&i.TaskCount,
			&i.MilestoneCount,
			&i.StrategyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, title, status, priority, milestone_id, summary, body, total_criteria, completed_criteria, filepath, mtime
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.MilestoneID,
		&i.Summary,
		&i.Body,
		&i.TotalCriteria,
		&i.CompletedCriteria,
		&i.Filepath,
		&i.Mtime,
	)
	return i, err
}

const getTaskDependencies = `-- name: GetTaskDependencies :many
SELECT depends_on_task_id
FROM task_dependencies
WHERE task_id = ?
ORDER BY depends_on_task_id ASC
`

func (q *Queries) GetTaskDependencies(ctx context.Context, taskID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTaskDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var depends_on_task_id string
		if err := rows.Scan(&depends_on_task_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnfinishedDependencies = `-- name: GetUnfinishedDependencies :many
SELECT t.id, t.title, t.status
FROM task_dependencies td
JOIN tasks t ON td.depends_on_task_id = t.id
WHERE td.task_id = ? AND t.status != 'done'
ORDER BY t.id ASC
`

type GetUnfinishedDependenciesRow struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
}

func (q *Queries) GetUnfinishedDependencies(ctx context.Context, taskID string) ([]GetUnfinishedDependenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnfinishedDependencies, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnfinishedDependenciesRow{}
	for rows.Next() {
		var i GetUnfinishedDependenciesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFTSEntity = `-- name: InsertFTSEntity :exec
INSERT INTO fts_entities (entity_type, entity_id, title, summary, body)
VALUES (?, ?, ?, ?, ?)
`

type InsertFTSEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Title      string `json:"title"`
	Summary    string `json:"summary"`
	Body       string `json:"body"`
}

// Full-Text Search (FTS5)
func (q *Queries) InsertFTSEntity(ctx context.Context, arg InsertFTSEntityParams) error {
	_, err := q.db.ExecContext(ctx, insertFTSEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Title,
		arg.Summary,
		arg.Body,
	)
	return err
}

const listGlossaryTerms = `-- name: ListGlossaryTerms :many
SELECT id, title, summary, body, filepath, mtime
FROM glossary
ORDER BY id ASC
`

func (q *Queries) ListGlossaryTerms(ctx context.Context) ([]Glossary, error) {
	rows, err := q.db.QueryContext(ctx, listGlossaryTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Glossary{}
	for rows.Next() {
		var i Glossary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Body,
			&i.Filepath,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, title, status, target_date, summary, body, filepath, mtime
FROM milestones
ORDER BY id ASC
`

func (q *Queries) ListMilestones(ctx context.Context) ([]Milestone, error) {
	rows, err := q.db.QueryContext(ctx, listMilestones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.TargetDate,
			&i.Summary,
			&i.Body,
			&i.Filepath,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategies = `-- name: ListStrategies :many
SELECT id, title, tier, summary, body, filepath, mtime
FROM strategies
ORDER BY tier ASC, id ASC
`

func (q *Queries) ListStrategies(ctx context.Context) ([]Strategy, error) {
	rows, err := q.db.QueryContext(ctx, listStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strategy{}
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Tier,
			&i.Summary,
			&i.Body,
			&i.Filepath,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategiesByTier = `-- name: ListStrategiesByTier :many
SELECT id, title, tier, summary, body, filepath, mtime
FROM strategies
WHERE tier = ?
ORDER BY id ASC
`

func (q *Queries) ListStrategiesByTier(ctx context.Context, tier int64) ([]Strategy, error) {
	rows, err := q.db.QueryContext(ctx, listStrategiesByTier, tier)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Strategy{}
	for rows.Next() {
		var i Strategy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Tier,
			&i.Summary,
			&i.Body,
			&i.Filepath,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, status, priority, milestone_id, summary, body, total_criteria, completed_criteria, filepath, mtime
FROM tasks
ORDER BY id ASC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.MilestoneID,
			&i.Summary,
			&i.Body,
			&i.TotalCriteria,
			&i.CompletedCriteria,
			&i.Filepath,
			&i.Mtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskCriteria = `-- name: UpdateTaskCriteria :exec
UPDATE tasks
SET total_criteria = ?, completed_criteria = ?, body = ?, mtime = ?
WHERE id = ?
`

type UpdateTaskCriteriaParams struct {
	TotalCriteria     int64  `json:"total_criteria"`
	CompletedCriteria int64  `json:"completed_criteria"`
	Body              string `json:"body"`
	Mtime             int64  `json:"mtime"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateTaskCriteria(ctx context.Context, arg UpdateTaskCriteriaParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskCriteria,
		arg.TotalCriteria,
		arg.CompletedCriteria,
		arg.Body,
		arg.Mtime,
		arg.ID,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = ?, mtime = ?
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string `json:"status"`
	Mtime  int64  `json:"mtime"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.Mtime, arg.ID)
	return err
}

const upsertGlossaryTerm = `-- name: UpsertGlossaryTerm :exec
INSERT INTO glossary (
    id, title, summary, body, filepath, mtime
) VALUES (
    ?, ?, ?, ?, ?, ?
) ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    summary = excluded.summary,
    body = excluded.body,
    filepath = excluded.filepath,
    mtime = excluded.mtime
`

type UpsertGlossaryTermParams struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Summary  string `json:"summary"`
	Body     string `json:"body"`
	Filepath string `json:"filepath"`
	Mtime    int64  `json:"mtime"`
}

// Glossary
func (q *Queries) UpsertGlossaryTerm(ctx context.Context, arg UpsertGlossaryTermParams) error {
	_, err := q.db.ExecContext(ctx, upsertGlossaryTerm,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Body,
		arg.Filepath,
		arg.Mtime,
	)
	return err
}

const upsertMilestone = `-- name: UpsertMilestone :exec
INSERT INTO milestones (
    id, title, status, target_date, summary, body, filepath, mtime
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    status = excluded.status,
    target_date = excluded.target_date,
    summary = excluded.summary,
    body = excluded.body,
    filepath = excluded.filepath,
    mtime = excluded.mtime
`

type UpsertMilestoneParams struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Status     string `json:"status"`
	TargetDate string `json:"target_date"`
	Summary    string `json:"summary"`
	Body       string `json:"body"`
	Filepath   string `json:"filepath"`
	Mtime      int64  `json:"mtime"`
}

// Milestones
func (q *Queries) UpsertMilestone(ctx context.Context, arg UpsertMilestoneParams) error {
	_, err := q.db.ExecContext(ctx, upsertMilestone,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.TargetDate,
		arg.Summary,
		arg.Body,
		arg.Filepath,
		arg.Mtime,
	)
	return err
}

const upsertStrategy = `-- name: UpsertStrategy :exec
INSERT INTO strategies (
    id, title, tier, summary, body, filepath, mtime
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    tier = excluded.tier,
    summary = excluded.summary,
    body = excluded.body,
    filepath = excluded.filepath,
    mtime = excluded.mtime
`

type UpsertStrategyParams struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Tier     int64  `json:"tier"`
	Summary  string `json:"summary"`
	Body     string `json:"body"`
	Filepath string `json:"filepath"`
	Mtime    int64  `json:"mtime"`
}

// Strategies
func (q *Queries) UpsertStrategy(ctx context.Context, arg UpsertStrategyParams) error {
	_, err := q.db.ExecContext(ctx, upsertStrategy,
		arg.ID,
		arg.Title,
		arg.Tier,
		arg.Summary,
		arg.Body,
		arg.Filepath,
		arg.Mtime,
	)
	return err
}

const upsertTask = `-- name: UpsertTask :exec
INSERT INTO tasks (
    id, title, status, priority, milestone_id, summary, body, total_criteria, completed_criteria, filepath, mtime
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    status = excluded.status,
    priority = excluded.priority,
    milestone_id = excluded.milestone_id,
    summary = excluded.summary,
    body = excluded.body,
    total_criteria = excluded.total_criteria,
    completed_criteria = excluded.completed_criteria,
    filepath = excluded.filepath,
    mtime = excluded.mtime
`

type UpsertTaskParams struct {
	ID                string `json:"id"`
	Title             string `json:"title"`
	Status            string `json:"status"`
	Priority          string `json:"priority"`
	MilestoneID       string `json:"milestone_id"`
	Summary           string `json:"summary"`
	Body              string `json:"body"`
	TotalCriteria     int64  `json:"total_criteria"`
	CompletedCriteria int64  `json:"completed_criteria"`
	Filepath          string `json:"filepath"`
	Mtime             int64  `json:"mtime"`
}

// Tasks
func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.ExecContext(ctx, upsertTask,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.MilestoneID,
		arg.Summary,
		arg.Body,
		arg.TotalCriteria,
		arg.CompletedCriteria,
		arg.Filepath,
		arg.Mtime,
	)
	return err
}
